forecastmanager/urls.py
from django.urls import path

from .views import (
    CityListView,
    ForecastListView,
    download_forecast_template,
    weather_icons,
    forecast_settings
)

urlpatterns = [
    path('api/cities', CityListView.as_view(), name='cities-list'),
    path('api/forecasts', ForecastListView.as_view(), name='forecast-list'),
    path('api/forecast-settings', forecast_settings, name='forecast-settings'),
    path('api/weather-icons', weather_icons, name='weather-icons'),
    path('api/forecast_templace.csv', download_forecast_template, name='download-forecast-template'),
]

forecastmanager/models.py
import uuid
from datetime import datetime

from django.contrib.gis.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_extensions.db.fields import AutoSlugField
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.panels import FieldPanel, InlinePanel
from wagtail.api.v2.utils import get_full_url
from wagtail.models import Orderable
from wagtailgeowidget import geocoders
from wagtailgeowidget.helpers import geosgeometry_str_to_struct
from wagtailgeowidget.panels import LeafletPanel, GeoAddressPanel

from .forecast_settings import (
    ForecastPeriod,
    WeatherCondition,
    ForecastDataParameters
)
from .forms import ForecastCreateForm


class City(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text=_("Unique UUID. Auto generated on creation."),
    )
    name = models.CharField(verbose_name=_("City Name"), max_length=255, null=True, blank=False, unique=True)
    slug = AutoSlugField(populate_from='name', null=True, unique=True, default=None, editable=False)
    location = models.PointField(verbose_name=_("City Location (Lat, Lng)"))
    panels = [
        GeoAddressPanel("name", geocoder=geocoders.NOMINATIM),
        LeafletPanel("location", address_field="name"),
    ]

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")
        ordering = ['name']

    def __str__(self):
        return self.name

    @property
    def coordinates(self):
        location = geosgeometry_str_to_struct(str(self.location))
        return [float(location['x']), float(location['y'])]

    @property
    def x(self):
        return self.coordinates[0]

    @property
    def y(self):
        return self.coordinates[1]


class Forecast(ClusterableModel):
    base_form_class = ForecastCreateForm

    FORECAST_SOURCE_CHOICES = [
        ("local", _("NMHSs Forecast")),
        ("yr", _("yr.no")),
    ]

    forecast_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name=_("Forecasts Date"))
    effective_period = models.ForeignKey(ForecastPeriod, on_delete=models.PROTECT, null=True)
    source = models.CharField(max_length=100, choices=FORECAST_SOURCE_CHOICES, default="local")

    class Meta:
        unique_together = ("forecast_date", "effective_period")
        verbose_name = _("Forecast")
        verbose_name_plural = _("Forecasts")
        ordering = ["forecast_date", "effective_period"]

    panels = [
        FieldPanel("forecast_date"),
        FieldPanel("effective_period"),
        FieldPanel("replace_existing"),
        # InlinePanel("city_forecasts", label=_("City Forecast Data")),
    ]

    def __str__(self):
        return f"{self.forecast_date} - {self.effective_period.label}"

    @property
    def datetime(self):
        return datetime.combine(self.forecast_date, self.effective_period.forecast_effective_time)

    def get_geojson(self, request=None):
        features = []
        for city_forecast in self.city_forecasts.all():
            features.append(city_forecast.get_geojson_feature(request))
        return {
            "type": "FeatureCollection",
            "date": self.forecast_date,
            "datetime": self.datetime,
            "features": features,
        }


class CityForecast(ClusterableModel, Orderable):
    parent = ParentalKey(Forecast, on_delete=models.CASCADE, related_name="city_forecasts")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name=_("City"))
    condition = models.ForeignKey(WeatherCondition, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("parent", "city")
        ordering = ["parent__forecast_date", "parent__effective_period"]

    panels = [
        FieldPanel("city"),
        FieldPanel("condition"),
        InlinePanel("data_values", label=_("Forecast Data Values")),
    ]

    def __str__(self):
        return f"{self.city.name} - {self.parent.forecast_date} - {self.parent.effective_period.label}"

    @property
    def forecast_date(self):
        return self.parent.forecast_date

    @property
    def effective_period(self):
        return self.parent.effective_period

    @cached_property
    def datetime(self):
        effective_period_time = self.effective_period.forecast_effective_time
        date = datetime.combine(self.forecast_date, effective_period_time)
        return timezone.make_aware(date)

    @property
    def data_values_dict(self):
        data_values = {}
        for data_value in self.data_values.all():
            parameter_info = data_value.parameter.parameter_info
            val = {
                "value": data_value.parsed_value,
                "name": data_value.parameter.name,
                "label": data_value.parameter.name,
                "units": data_value.parameter.units,
                "value_with_units": data_value.value_with_units,
            }

            if parameter_info:
                val.update({
                    "icon": data_value.parameter.parameter_info.get("icon"),
                })

            data_values[data_value.parameter.parameter] = val

        return data_values

    def get_geojson_feature(self, request=None):
        condition_symbol_url = get_full_url(request, self.condition.icon_url)

        feature = {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": self.city.coordinates,
            },
            "properties": {
                "date": self.parent.datetime,
                "effective_period_time": self.parent.effective_period.forecast_effective_time,
                "effective_period_label": self.parent.effective_period.label,
                "city": self.city.name,
                "city_slug": self.city.slug,
                "condition": self.condition.symbol,
                "condition_label": self.condition.label,
                "condition_symbol_url": condition_symbol_url
            },
        }

        parameter_values = {}
        for data_value in self.data_values.all():
            parameter_values[data_value.parameter.parameter] = data_value.parsed_value

        feature["properties"].update(parameter_values)

        return feature


class DataValue(ClusterableModel, Orderable):
    parent = ParentalKey(CityForecast, on_delete=models.CASCADE, related_name="data_values")
    parameter = models.ForeignKey(ForecastDataParameters, on_delete=models.CASCADE, related_name="data_values")
    value = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Value"))

    class Meta:
        unique_together = ("parent", "parameter")

    @property
    def parsed_value(self):
        return self.parameter.parse_value(self.value)

    @property
    def value_with_units(self):
        if self.parsed_value is None:
            return None

        if not self.parameter.units:
            return self.parsed_value

        return f"{self.parsed_value} {self.parameter.units}"

forecastmanager/templates/forecastmanager/create_forecast.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags static %}
{% block titletag %}{% blocktrans trimmed with snippet_type_name=model_opts.verbose_name %}New  {{ snippet_type_name }}
{% endblocktrans %}{% endblock %}
{% block content %}
    {% include 'wagtailadmin/shared/headers/slim_header.html' %}

    {% trans "New" as new_str %}
    {% include "wagtailadmin/shared/header.html" with title=new_str subtitle=model_opts.verbose_name icon=header_icon merged=1 only %}


    <div class="nice-padding">
        <div class="help-block help-info">
            <svg class="icon icon-warning icon" aria-hidden="true">
                <use href="#icon-info-circle"></use>
            </svg>
            <div>
                {% trans 'You can' %}
                <a href="{% url 'download-forecast-template' %}">
                    <b>{% trans 'download a template' %}</b>
                </a>
                {% trans 'of the CSV for offline editing and upload it here. The template comes prepopulated with all pre-exisiting cities.' %}
            </div>
        </div>
    </div>

    <div class="row row-flush" style="padding-top:1rem">
        <div class="col5">
            <form id="forecast-form"
                  action="{{ action_url }}"
                  method="POST"
                  novalidate{% if form.is_multipart %}
                  enctype="multipart/form-data"{% endif %}
                  data-edit-form
            >
                {% csrf_token %}

                <div class="nice-padding">
                    {{ panel.render_form_content }}
                </div>

                <footer class="footer">
                    <nav aria-label="{% trans 'Actions' %}">
                        <ul>
                            <li class="actions actions--primary footer__container">
                                <div class="dropdown dropup dropdown-button match-width">
                                    {{ action_menu.render_html }}
                                </div>
                            </li>
                        </ul>
                    </nav>
                </footer>
            </form>
            <div class="nice-padding">
                {% include "forecastmanager/file_input_include.html" %}
            </div>
        </div>
        <div class="col7">
            <div class="right-panel"
                 style="margin-right: 40px;">
                <div id="match-fields" style="display: none">
                    <h2>Match Fields</h2>
                    <div class="help-block help-info">
                        <svg class="icon icon-warning icon" aria-hidden="true">
                            <use href="#icon-info-circle"></use>
                        </svg>
                        <div>
                            {% trans 'Verify that all columns match correctly' %}
                        </div>
                    </div>
                    <ul class="param-selectors">
                        <li class="selector">
                            <label for="city" class="w-field__label">{% trans 'City' %}:</label>
                            <div class="w-field w-field--file_field w-field--file_input">
                                <div class="w-field__input" data-field-input="">
                                    <select id="city">
                                    </select>
                                </div>
                            </div>
                        </li>
                        {% for param in parameters %}
                            <li class="selector">
                                <label for="{{ param.parameter }}" class="w-field__label">{{ param.name }}:
                                </label>
                                <div class="w-field w-field--file_field w-field--file_input">
                                    <div class="w-field__input" data-field-input="">
                                        <select id="{{ param.parameter }}">
                                        </select>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                        <li class="selector">
                            <label for="condition" class="w-field__label">{% trans 'Condition' %}: </label>
                            <div class="w-field w-field--file_field w-field--file_input">
                                <div class="w-field__input" data-field-input="">
                                    <select id="condition">
                                    </select>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div id="table-container" class="hot handsontable"></div>
            </div>
        </div>

    </div>





{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ media.css }}

    <link rel="stylesheet" type="text/css" href="{% static 'forecastmanager/css/handsontable.full.min.css' %}">

    <style>
        .forecast,
        select {
            font-size: 14px
        }

        .param-selectors {
            display: flex;
            flex-wrap: wrap;
            padding: 0;

        }

        .param-selectors .selector {
            list-style: none;
            width: 200px;
            padding-bottom: 20px
        }


    </style>



{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}

    <script src="{% static 'forecastmanager/js/handsontable.full.min.js' %}"></script>
    <script src="{% static 'forecastmanager/js/data-utils.js' %}"></script>
    <script src="{% static 'forecastmanager/js/helpers.js' %}"></script>

    <script>
        const parameters = {{parameters|safe}};
        const weather_conditions = {{weather_conditions|safe}};
        const cities = {{cities|safe}};


        function HotLoader(options) {
            const {
                tableContainerId,
                fileInputId,
                matchFieldsId,
                submitButton,
                parameters,
                dataInputId,
                cities,
                weatherConditions
            } = options;


            const tableContainer = document.getElementById(tableContainerId);
            this.fileInput = document.getElementById(fileInputId);
            this.matchFields = document.getElementById(matchFieldsId);
            this.dataInput = document.getElementById(dataInputId);
            this.submitBtn = submitButton;

            this.parameters = parameters;


            this.hot = new Handsontable(tableContainer, {
                autoWrapRow: true,
                autoWrapCol: true,
                rowHeaders: true,
                colHeaders: [
                    'City',
                    ...this.parameters.map(p => p.name),
                    'Condition'
                ],
                columns: [
                    {
                        type: 'dropdown',
                        source: cities.map(city => city.name),
                        allowEmpty: false,
                        allowInvalid: false,
                    },
                    ...this.parameters.map((p) => ({
                        type: p.parameter_type,
                        allowEmpty: true,
                        allowInvalid: false,
                    })),
                    {
                        type: 'dropdown',
                        source: weatherConditions,
                        allowEmpty: false,
                        allowInvalid: false,
                    },
                ],
                contextMenu: true,
                licenseKey: 'non-commercial-and-evaluation',
                height: 500,
                startRows: 1,
                afterRemoveRow: (index, amount) => {
                    this.hot.validateCells(this.onValidate.bind(this));
                },

                afterChange: (changes, source) => {
                    this.onChange();
                }
            });


            this.columnSelectors = [
                {
                    dom_id: 'city',
                    index: 0
                },
                ...this.parameters.map((p, i) => ({
                    dom_id: p.parameter,
                    index: i + 1
                })),
                {
                    dom_id: 'condition',
                    index: this.parameters.length + 1
                },
            ]

            this.fileInput.addEventListener('change', this.onFileChange.bind(this));
        }


        HotLoader.prototype.onFileChange = function (e) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.readAsText(file);

            const that = this

            reader.onload = function (event) {
                DataUtils.parseCSV(event.target.result).then(parsedData => {
                    const initialData = parsedData.rows

                    that.hot.updateData(initialData);

                    const columnHeaders = parsedData.fields.map(field => field.name);

                    that.columnSelectors.forEach(column => {
                        generateSelectInput(column.dom_id, columnHeaders, column.index)
                        document.getElementById(column.dom_id).addEventListener('change', that.onColumnDataSwap.bind(that, column, initialData))
                        return column
                    })

                    that.matchFields.style.display = 'block'
                });
            };
        };

        HotLoader.prototype.onColumnDataSwap = function (column, initialData, e) {
            const tableData = this.hot.getData();

            const columnArray = initialData.map(arr => {
                return arr[e.target.value]
            })

            tableData.replace_data(column.index, columnArray)

            this.hot.updateData(tableData)
        }

        HotLoader.prototype.onChange = function () {
            if (!this.hot) {
                return
            }

            this.hot.validateCells(this.onValidate.bind(this));
        }

        HotLoader.prototype.onValidate = function (isValid) {

            if (!isValid) {
                this.submitBtn.disabled = true;
                return
            }

            const colHeader = this.hot.getColHeader();
            const data = this.hot.getData();

            const tableData = {
                fields: colHeader,
                rows: data
            }

            if (data && data.length === 0) {
                this.submitBtn.disabled = true;
                return
            }

            this.dataInput.value = JSON.stringify(tableData)
            this.submitBtn.disabled = false;
        }

        $(document).ready(function () {
            const parameters = {{parameters|safe}};
            const weatherConditions = {{weather_conditions|safe}};
            const cities = {{cities|safe}};


            const submitBtnSelector = "#forecast-form button[type='submit']";
            const submitBtn = document.querySelector(submitBtnSelector);
            // disable submit button by default
            submitBtn.disabled = true;

            const hotLoader = new HotLoader({
                tableContainerId: 'table-container',
                fileInputId: 'id_file',
                matchFieldsId: 'match-fields',
                parameters,
                dataInputId: 'id_data',
                cities,
                weatherConditions,
                submitButton: submitBtn
            });


        });
    </script>
    <script>
        // Set wagtailConfig.ACTIVE_CONTENT_LOCALE if this is a translated page
        // This value may be used by JS widgets on the form
        {% if locale %}
            window.wagtailConfig = window.wagtailConfig || {};
            window.wagtailConfig.ACTIVE_CONTENT_LOCALE = '{{ locale.language_code|escapejs }}';
        {% endif %}
    </script>
{% endblock %}

forecastmanager/templates/forecastmanager/view_forecast.html
{% extends 'forecastmanager/forecast_base.html' %}
{% load wagtailadmin_tags i18n static %}
{% load wagtailsettings_tags %}
{% get_settings use_default_site=True %}

{% block extra_css %}
    {{ block.super }}
    <style>
        #forecast_map {
            height: 60vh;
            width: 100%;
            box-shadow: 0px 0px 7px 0px rgba(0, 0, 0, 0.1);
        }
    </style>
{% endblock extra_css %}

{% block header %}
    {% trans 'View Forecasts' as header_str %}
    {% trans 'Add Forecasts' as add_forecast %}
    {% url 'add_forecast' as add_forecast_url %}
    {% include "wagtailadmin/shared/header.html" with title=header_str icon="form" action_url=add_forecast_url action_text=add_forecast %}
{% endblock %}

{% block forecast %}
    <h2 class="w-panel__heading" style="margin-bottom: 20px">{% trans 'Latest Available Forecast' %}</h2>
    <div class="row row-flush" style="display:flex; align-items:baseline">
        <div class="col6" style="display:flex; flex-wrap: wrap;">
            <div class="w-field__wrapper " data-field-wrapper="" style="padding-right:1em">
                <label class="w-field__label" for="id_forecast_date" id="id_forecast_date-label">
                    {% trans 'Forecast Date' %}<span class="w-required-mark">*</span>
                </label>
                <div class="w-field w-field--choice_field w-field--select" data-field="" data-contentpath="select">
                    <div class="w-field__input" data-field-input="">
                        <select name="forecast_date" id="id_forecast_date">
                            {% for day in forecast_dates %}
                                <option value="{{ day|date:'Y-m-d' }}"
                                        {% if forloop.first %}selected{% endif %}>{{ day }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="w-field__wrapper " data-field-wrapper="">
                <label class="w-field__label" for="id_effective_period" id="id_effective_period-label">
                    {% trans 'Forecast Effective Period' %}<span class="w-required-mark">*</span>
                </label>
                <div class="w-field w-field--choice_field w-field--select" data-field="" data-contentpath="select">
                    <div class="w-field__input" data-field-input="">
                        <select name="select" id="id_effective_period">
                            {% for period in forecast_periods.all %}
                                <option value="{{ period.pk }}"
                                        {% if forloop.first %}selected{% endif %}>{{ period.label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="padding:2em 0">
        <div class="row row-flush">
            <div class="col7">
                <div id="latestForecast" style=z-index:1></div>
            </div>
            <div class="col5">
                <div id="forecast_map"></div>
            </div>
        </div>
    </div>
{% endblock forecast %}


{% block extra_js %}
    {{ block.super }}

    <script type="text/javascript">

        const dataParams = {{ data_parameter_values|safe|default_if_none:"" }};


        $(document).ready(function () {
            const static_path = '{% static "forecastmanager/img/" %}'

            const $dateInput = $("#id_forecast_date");
            const $periodInput = $("#id_effective_period");

            const forecastContainer = document.getElementById('latestForecast');

            // initialize map     
            const forecastMap = new maplibregl.Map({
                container: 'forecast_map',
                style: basemap,
                center: [39.67458166409534, 8.709054632756391],
                zoom: 4.5
            })

            // Create a popup object
            const popup = new maplibregl.Popup({
                closeButton: false,
                closeOnClick: false
            });

            forecastMap.addControl(new maplibregl.NavigationControl())

            // initialize
            getForecastData()

            // initialize table
            const forecastTable = new Handsontable(forecastContainer, {
                readOnly: true,
                width: '100%',
                rowHeaders: true,
                colHeaders: [
                    'City',
                    ...dataParams.map(p => p.name),
                    'Condition'
                ],
                columns: [
                    {
                        data: 'city_name',
                    },
                    ...dataParams.map((p) => ({
                        data: p.parameter,
                        type: p.parameter_type,
                        timeFormat: 'h:mm' ? p.parameter_type === 'time' : '',
                        correctFormat: true,
                    })),
                    {
                        data: 'condition',
                    },
                ],
                data: [],
                // dropdownMenu: true,
                multiColumnSorting: true,
                // filters: true,
                manualColumnResize: true,
                minSpareRows: 1,
                height: 'auto',
                stretchH: "all",
                licenseKey: 'non-commercial-and-evaluation' // for non-commercial use only
            });


            function populateMap(data) {

                if(forecastMap.getLayer("city-forecasts")){
                    forecastMap.removeLayer("city-forecasts")
                }

                if(forecastMap.getSource("city-forecasts")){
                    forecastMap.removeSource("city-forecasts")

                }
                if(data.features.length >0){
                    forecastMap.addSource("city-forecasts", {
                        type: "geojson",
                        data: data
                    })
    
                    forecastMap.addLayer({
                        "id": "city-forecasts",
                        "type": "symbol",
                        "layout": {
                            'icon-image': ['get', 'condition_icon'],
                            'icon-size': 0.3,
                            'icon-allow-overlap': true
                        },
                        source: "city-forecasts"
                    })
    
                    const bbox = turf.bbox(data)
    
                    forecastMap.fitBounds(bbox, {
                        padding: {top: 100, bottom: 100, left: 100, right: 100},
                        duration: 1000,
                        easing: function (t) {
                            return t * (2 - t); // Cubic easing function
                        }
                    })
                }
               
            }

            function getForecastData() {
                const forecastDate = $dateInput.val()
                const effectivePeriod = $periodInput.val()


                if (forecastDate || effectivePeriod) {
                    // Make an HTTP GET request to the API endpoint
                    fetch(`{% url 'forecast-list'%}?forecast_date=${forecastDate}&effective_period=${effectivePeriod}`)
                        .then(response => response.json())  // Parse the response as JSON
                        .then(data => {
                            // Process the retrieved data
                            data.map(icon => {
                                let img = new Image()
                                img.onload = () => {
                                    if (!forecastMap.hasImage(icon.properties.condition_icon)) {
                                        return forecastMap.addImage(`${icon.properties.condition_icon}`, img)
                                    }

                                }
                                img.src = `${static_path}${icon.properties.condition_icon}`
                                return img.src

                            })
                            // Access and use the data as needed
                            populateMap({
                                type: "FeatureCollection",
                                features: data
                            })

                            const forecasts_props = []
                            data.map(latest_forecast => {
                                forecasts_props.push(latest_forecast.properties)
                            })

                            forecastTable.loadData(forecasts_props)
                        })
                        .catch(error => {
                            // Handle any errors that occurred during the request
                            console.error('Error:', error);
                        });
                }
            }


            const getPopupHTML = (props) => {
                const paramValues = dataParams.reduce((all, param) => {
                    if (props[param.parameter]) {
                        all[param.name] = `${props[param.parameter]} ${param.parameter_unit}`
                    }
                    return all
                }, {})

                const cityName = props.city_name;
                const condition = props.condition;

                let values = Object.keys(paramValues).reduce((all, key) => {
                    all = all + `<p><b>${key}: </b>${paramValues[key]}</p>`
                    return all
                }, "")

                return `<div class="block" style="margin:10px; width:200px">
                    <h2 class="title" style="font-size:18px;">${cityName}</h2>
                    <h2 class="subtitle" style="font-size:14px;">${condition}</h2>
                    <hr>
                    ${values}
                </div>`
            }

            forecastMap.on("load", () => {
                // When a click event occurs on a feature in the places layer, open a popup at the
                // location of the feature, with description HTML from its properties.
                forecastMap.on("mouseenter", "city-forecasts", (e) => {
                    // Get the feature that was hovered over
                    const feature = e.features[0];
                    forecastMap.getCanvas().style.cursor = "pointer";

                    popup.setLngLat(feature.geometry.coordinates)
                        .setHTML(getPopupHTML(feature.properties))
                        .addTo(forecastMap);
                });

                // // Change the cursor to a pointer when the mouse is over the places layer.
                // forecastMap.on("mouseenter", "city-forecasts", () => {
                //     forecastMap.getCanvas().style.cursor = "pointer";
                // });

                // Change it back to a pointer when it leaves.
                forecastMap.on("mouseleave", "city-forecasts", () => {
                    popup.remove()
                    forecastMap.getCanvas().style.cursor = "";
                });
            })

            $dateInput.on('change', (e) => {
                getForecastData()
            })

            $periodInput.on('change', (e) => {
                getForecastData()
            })
        })
    </script>
{% endblock extra_js %}